### ISSUE TITLE
Player disconnect

### ISSUE THREAD

**Issue by justdprroz** [light-merch/TRON_multiplayer#30]
if you properly exit the game using ctrl+W or cross, the player disconnects. If I exit the browser or reload the page player doesn't disconnect. The player should leave the game on reload or closing browser

**Comment by pavtiger** [comment]
I already check tab close events but the browser close can be fixed by deleting a user after a few dozens of seconds of idle activity

**Comment by pavtiger** [comment]
If a player loses internet connection, we should also disconnect him
